.tab td div {
	max-height: none !important;
}
.x-window-header-text {
    height: 28px;
    line-height: 28px;
    ~vertical-align: middle;
	~padding: 4 0 0 8px;
}
#labelForCampaignSelectInputx {
    color: #4A4A56;
    font-size: 91%;
    font-weight: bold;
    text-align: right;
	font-family: Arial, Helvetica, sans-serif;
}
#campaignSelectInputx {
    margin: 0;
    padding: 0;
    margin-right: 0.25em;
    ~vertical-align: middle;
    font-family: Arial, Helvetica, sans-serif;
}
.x-window-body {
	background: url("/img/alohaSkin/lookup_bg.png") repeat-x scroll 0 0 #FFFFFF;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 0.9em;
	font-weight: bold;
}
.x-window-header-text {
	height: 24px;
	line-height: 24px;
	vertical-align: middle;
	margin-top: 1px;
	margin-left: 8px;
}
.x-window-header {
	border-radius: 5px 5px 0px 0px;
	background: url("/img/alohaSkin/lookup_bg.png") repeat-x scroll 0 0 #FFFFFF;
	margin: 1 1 0 1;            
}
.x-grid-header-ct {
	border-top: 3px solid #737E96;
	border-radius: 4px 4px 0px 0px;
}
.x-grid-body {
	border-radius: 0px 0px 4px 4px;
}
.x-column-header-inner {
	background: url("/img/alohaSkin/grid_headerbg.gif") repeat-x scroll 0 bottom #FFFFFF;
	border-width: 0 0 1px 1px;
	padding: 5px 2px 4px 5px;
	color: #000000;
}
.x-panel-body {
	border-style: none;
}
.x-btn {
	background: url("/img/alohaSkin/btn_sprite.png") repeat-x scroll right top #E8E8E9;
	border-color: #B5B5B5 #B5B5B5 #7F7F7F;
	border-radius: 3px 3px 3px 3px;
	border-style: solid;
	border-width: 1px;
	color: #333333;
	margin: 1px;
	padding: 2px 3px;
}
#labelForFilterInputField {
	color: #4A4A56;
}
.x-btn-inner {
	color: #333333;
}
.boldText{
	font-weight:bold
}
.pageBlockExt {
    margin: 7px 0 !important;
}
.contact-panel {
    padding-top: 15px !important;
    padding-bottom: 15px !important;
}
.user-title {
    font-weight:bold;
    font-size: 1.3em;
}
.x-border-box .x-reset, .x-border-box .x-reset *{
	box-sizing: inherit;
   	-webkit-box-sizing: inherit;
}
#app-calendar-data {
    width: 100% !important;
    height: 100% !important;
    background-color: red;
}
#calendar-form {
    min-height:710px;
    height:auto !important;            
    width: 100%;    
}
#ext-cal-nav-picker {
    border-left: 1px solid;     
}
div.x-toolbar.x-small-editor.ext-cal-toolbar.x-toolbar-layout-ct
{
    border-top-width: 0px; 
    border-left-width: 0px; 
    border-right-width: 1px;
}
div.x-date-picker.x-unselectable.ext-cal-nav-picker.x-border-panel
{
	border-bottom-width: 0px; 
    border-left-width: 1px;
    border-color: #1B376C !important;
} 
td.x-date-left, td.x-date-right 
{
    vertical-align: middle;
}
div.x-window.ext-cal-event-win 
{
    background-color: #99BBE8;
}
div#app-header {
    display: block;
    text-align:left;        
}
 div#app-header h1 
{
    color: #455C6F;     
    font-size: 18px;
    font-style: bold;
    margin: 8px 5px;    
    display: block;
}
.ext-cal-ev {
    height: 20px;
}
.ext-cal-dtitle.ext-cal-dtitle-first {
    height: 17px;
    margin: 8px 1px 2px 1px;
} 
#app-center {
    width: 100% !important;
}
#app-center .x-panel-body.x-border-layout-ct {
    width: 100% !important;
}