/*button customization*/
.x-btn.x-btn-noicon, #app-calendar-tb-prev, #app-calendar-tb-next {
    padding: 0px;
    margin: 0px;
    border-width: 0px;
    background-color: transparent;
    backgorund-image: none;
}
.x-window-header {	
	background: none !important;
}
.x-window-body {
	background: none !important;
}
.x-column-header-inner {
	background: none !important;
}
.x-window-header {
    background: none !important;
}
.x-date-mp-btns .x-date-mp-ok, .x-date-mp-btns .x-date-mp-cancel {
    color: #000 !important;
}
.x-btn-small.x-btn-icon-small-left {
    border-color: #808080;
} 
/************************************/
.x-btn-text {
    background-image: none;
    background-position: 0 0;
    background-repeat: repeat;
}
/************************************/
 
         
 /* Show edit window*/
 div .x-window-tr {
    padding: 3px 6px 3px 12px;
    font: bold 9px tahoma,arial,verdana,sans-serif;     
 }
 
 div.x-dd-drop-icon {    
    left: 3px !important;
    top: 3px !important;
}