td.columnsone {
	width: 100%;
}

td.columnstwo {
	width: 50%;
}

td.columnsthree {
	width: 33%;
}

td.columnsfour {
	width: 25%;
}

td.columnsfive {
	width: 20%;
}

td.columnssix {
	width: 16%;
}

.columncenter {

	margin-left:auto;
	margin-right:auto;
	text-align:center;
	vertical-align: bottom;

}


.columncenter table {
	margin-left:auto;
	margin-right:auto;
	text-align:center;
	vertical-align: bottom;


	
}

td.campaignselect {
	
	margin-left:auto;
	margin-right:auto;
	text-align:center;
	vertical-align: bottom;
	color:#333333;
	font-size:91%;
	font-weight:bold;
	padding:2px 10px 2px 2px;

	
}