html, body {
    margin: 0px;
    padding: 0px;
    height: 100%;
    overflow: hidden;
    font-family: 'Salesforce Sans',Arial,sans-serif;
}

.dhx_title {
    font-size: 11px !important;
    padding-top: 5px !important;
    white-space: pre-wrap !important;
    word-wrap: break-word !important;
    text-overflow: ellipsis !important;
}

.dhx_body {
    padding-bottom: 3px !important;
    line-height: 15px !important;
    text-align: center !important;
    font-size: 11px !important;
    white-space: pre-wrap;
    overflow: hidden;
    word-wrap: break-word !important;
}

.dhx_cal_event .dhx_footer {
    background: none !important;

}
.dhx_cal_container {
    position: absolute;
}
.eventStatusNew .dhx_title,
.eventStatusNew .dhx_body {
    background: #A7E2D6;
    color: #1B615E;
}

.eventStatusAssigned .dhx_title,
.eventStatusAssigned .dhx_body {
    background: #FFCE36;
    color: #644D06;
}

.eventStatusDispatched .dhx_body,
.eventStatusDispatched .dhx_title {
    background: #92D9F7;
    color: #125977;
}

.eventStatusTravel .dhx_body,
.eventStatusTravel .dhx_title {
    background: #D495F4;
    color: #60206C;
}

.eventStatusOnSite .dhx_body,
.eventStatusOnSite .dhx_title {
    background: #D8C68B;
    color: #352404;
}

.eventStatusCompleted .dhx_body,
.eventStatusCompleted .dhx_title {
    background: #A3DF6D;
    color: #1C6708;
}

.eventStatusIncomplete .dhx_body,
.eventStatusIncomplete .dhx_title {
    background: #F27D7D;
    color: #3A0707;
}

.eventCustomStatus .dhx_body,
.eventCustomStatus .dhx_title {
    background: #B7C9EA;
    color: #2D3542;
}

.NA_Break .dhx_body {
    background: -webkit-repeating-linear-gradient(45deg, #5e698f, #5e698f 12.5px, #535C7D 12.5px, #535C7D 25px) !important;
    background: repeating-linear-gradient(45deg, #5e698f, #5e698f 12.5px, #535C7D 12.5px, #535C7D 25px) !important;
}

.NA_Break .dhx_title {
    background: rgb(83, 92, 125) !important;
    padding: 3px 0 2px 0 !important;
    text-overflow: ellipsis !important;
    white-space: nowrap !important;
}

.NA_Break .dhx_body a,
.NA_Break .dhx_title a {
    color: #fff;
}

.NA_Absence_NoTravel .dhx_title {
    color: #3A0707;
    background: #D7DFE7 !important;
    padding: 2px 0 3px 0 !important;
    text-overflow: ellipsis !important;
    white-space: nowrap !important;
}

.NA_Absence_Monthly,
.NA_Absence_NoTravel .dhx_body {
    background: -webkit-repeating-linear-gradient(45deg, rgba(215, 223, 231, 1), rgba(215, 223, 231, 1) 12.5px, rgba(206, 214, 221, 1) 12.5px, rgba(206, 214, 221, 1) 25px) !important;
    background: repeating-linear-gradient(45deg, rgba(215, 223, 231, 1), rgba(215, 223, 231, 1) 12.5px, rgba(206, 214, 221, 1) 12.5px, rgba(206, 214, 221, 1) 25px) !important;
    color: #3A0707;
}
.dhx_cal_event_line.eventStatusNew {
    background: #A7E2D6;
    color: #1B615E;
}

.dhx_cal_event_line.eventStatusAssigned {
    background: #FFCE36;
    color: #644D06;
}

.dhx_cal_event_line.eventStatusDispatched {
    background: #92D9F7;
    color: #125977;
}

.dhx_cal_event_line.eventStatusTravel {
    background: #D495F4;
    color: #60206C;
}

.dhx_cal_event_line.eventStatusOnSite {
    background: #D8C68B;
    color: #352404;
}

.dhx_cal_event_line.eventStatusCompleted {
    background: #A3DF6D;
    color: #1C6708;
}
.dhx_cal_event.eventStatusCompleted {
    background: #A3DF6D;
    color: #1C6708;
}

.dhx_cal_event_line.eventStatusIncomplete {
    background: #F27D7D;
    color: #3A0707;
}

.dhx_cal_event_clear.dhx_cal_event_line_start.dhx_cal_event_line_end {
    text-overflow: ellipsis !important;
    white-space: nowrap !important;
}

.dhx_cal_event_clear.dhx_cal_event_line_start.dhx_cal_event_line_end.eventStatusNew {
    background: #A7E2D6;
    color: #1B615E;
}

.dhx_cal_event_clear.dhx_cal_event_line_start.dhx_cal_event_line_end.eventStatusAssigned {
    background: #FFCE36;
    color: #125977;
}

.dhx_cal_event_clear.dhx_cal_event_line_start.dhx_cal_event_line_end.eventStatusDispatched {
    background: #92D9F7;
    color: #125977;
}

.dhx_cal_event_clear.dhx_cal_event_line_start.dhx_cal_event_line_end.eventStatusTravel {
    background: #D495F4;
    color: #60206C;
}

.dhx_cal_event_clear.dhx_cal_event_line_start.dhx_cal_event_line_end.eventStatusOnSite {
    background: #D8C68B;
    color: #352404;
}

.dhx_cal_event_clear.dhx_cal_event_line_start.dhx_cal_event_line_end.eventStatusCompleted {
    background: #A3DF6D;
    color: #1C6708;
}

.dhx_cal_event_clear.dhx_cal_event_line_start.dhx_cal_event_line_end.eventStatusIncomplete {
    background: #F27D7D;
    color: #3A0707;
}


.dhx_cal_event_line.dhx_cal_event_line_start.NA_Break,.dhx_cal_event_line.dhx_cal_event_line_end.NA_Break{
     background: -webkit-repeating-linear-gradient(45deg, #5e698f, #5e698f 12.5px, #535C7D 12.5px, #535C7D 25px) !important;
     background: repeating-linear-gradient(45deg, #5e698f, #5e698f 12.5px, #535C7D 12.5px, #535C7D 25px) !important;
      color: #fff;
}

#businessHours {
    position: relative;
    top: 20px;
    right: 140px;
    z-index: 10;
    float: right;
}

#yearGradient {
    position: fixed;
    top: 18px;
    right: 106px;
    z-index: 10;
    height: 30px;
    display: none;
}


#yearGradient span {
    display: inline-block;
    width: 10px;
    height: 10px;
    margin: 6px 8px 0 12px;
}

.LegendHigh { background: rgba(125, 195, 125, 1); }
.LegendMed { background: rgba(125, 195, 125, 0.5); }
.LegendLow { background: rgba(125, 195, 125, 0.25); }
.LegendNA { background: #ccc; }

#Apply {
    display: inline-block;
    color: #fff;
    font-size: 12px;
    position: relative;
    top: -6px;
    cursor: pointer;
    border-radius: 0 3px 3px 0;
    border: 1px solid #D8DDE6;
    padding: 6px;
    right: 6px;
}

#Apply:hover {
    background-color: #f4f6f9 !important;
}

#Apply svg {
    width: 18px;
    height: 18px;
    fill: #16325c;
}

.dhx_cal_today_button {
    width: 53px !important;
    right: 49px !important;
    text-overflow: ellipsis !important;
    white-space: pre-wrap !important;
    border-radius: 0 !important;
    border-color: #D8DDE6 !important;
}

.dhx_tooltip_line .dhx_event_icon {
    cursor: auto !important;

}

.dhx_cal_prev_button,
.dhx_cal_next_button {
    width: 34px !important;
    border-color: #D8DDE6 !important;
}

.dhx_cal_prev_button {
    right: 103px !important;
}

.lightboxLabel {
    color: #676767;
    font-size: 12px;
    margin-bottom: 3px;
    display: block;
}

.LightboxPopUp {
    position: absolute;
    top: 51px;
    left: 239px;
    z-index: 10001;
    background-color: white;
    width: 236px;
    box-shadow: 10px 10px 5px -8px rgba(0, 0, 0, 0.75);
    border-radius: 3px;
    border: 1px solid #CCC;

}

.LightboxHeader {
    background: #fff;
    padding: 8px;
    border-bottom: 2px solid #D8DDE6;
}

.LightboxName {
    color: #55698D;
    font-size: 19px;
}

.LightboxClose {
    right: 9px;
    position: absolute;
    top: 8px;
    color: #55698D;
    border-radius: 50%;
    padding: 3px 5px;
    background: #fff;
    cursor: pointer;
}

.LighboxContent {
    padding: 15px;
}

.fieldRow {
    margin-bottom: 10px;
    display: inline-table;
}

#leftside {
    display: inline-table;
}

#leftside .fieldRow input {
    border-radius: 3px;
    border: 1px solid #CCC;
    padding: 5px;
    width: 26px;
}

#leftside .fieldRow select {
    border-radius: 3px;
    border: 1px solid #CCC;
    padding: 5px;
    width: 70px;
    margin-right: 22px;
}

.LightboxButtons {
    border-radius: 0 0 3px 3px;
    padding: 0 10px 10px 10px;
}

.Btn {
    background: #0877bd;
    padding: 8px;
    width: 100px;
    font-size: 14px;
    color: #fff;
    text-align: center;
    margin: 0 auto;
    border-radius: 3px;
    cursor: pointer;
    /* margin-bottom: 10px;*/
    margin-top: 13px; /**/
}

.printIcon {
    position: absolute;
    color: #B4AEAC !important;
    background: #fff;
    cursor: pointer !important;
    top: 10px;
    margin-left: 254px !important;
    margin-top: 5px !important;
}

#rightside {
    display: inline-block;
    width: 162px;
    margin-left: 42px;
    position: relative;
    top: -2px;
}

.dhx_year_tooltip {
    width: 450px !important;
}

.tooltipLine {
    color: #222;
    margin: 4px 0;
}

.tooltipHR {
    height: 1px;
    width: 100%;
    background: #D5D5D5;
    margin: 12px 0;
}

.tooltipCell {
    display: inline-block;
    width: 105px;
}

.tooltipTitle {
    font-weight: bold;
}

.expertTooltip {
    border: 1px solid #CECECE;
    box-shadow: 2px 2px 5px #CCC !important;
    border-radius: 3px;
    color: #1c1c1c;
    max-width: 500px;
    padding: 0 !important;
}

.tooltipBody {
    padding: 8px 10px;
}

.tooltipBreakIcon {
    width: 17px !important;
    height: 17px !important;
}

.tooltipNAIcon {
    width: 15px !important;
    height: 15px !important;
}
.tooltipMultiDayIcon {
    width: 14px !important;
    height: 14px !important;
}

.naIcon {
    width: 12px !important;
    height: 12px !important;
    float: left;
    position: relative;
    margin: 1px 0 0 2px;
}

.breakIcon {
    width: 14px !important;
    height: 14px !important;
    float: left;
    position: relative;
    margin: -2px 0 0 2px;
}
.multiDay{
    width: 12px !important;
    height: 12px !important;
    float: left;
    position: relative;
    margin-top: -4px;
    margin-right: -2px;
    margin-bottom: 0px;
    margin-left: 2px;
}
.multiDayYearTt{
    width: 10px !important;
    height: 10px !important;
    float: left;
    position: relative;
    margin-top: 4px;
    margin-right: 0px;
    margin-bottom: 0px;
    margin-left: -2px;
}
  /*.low_util.dhx_year_event {
    background: rgba(125, 195, 125, 0.25) !important;
  }
  .medium_util.dhx_year_event {
    background:rgba(125, 195, 125, 0.5) !important;
 }
 .high_util.dhx_year_event {
    background: rgba(125, 195, 125, 1) !important;
}*/

/* .dhx_scheduler_year .dhx_month_head,.dhx_after{
    background-color: inherit !important;
  }*/

.NA_Absence_NoTravel {
    background-color: #ccc;
}

.low_util {
    background: rgba(125, 195, 125, 0.25);
   
}

.low_utilNA_Absence {
    background: linear-gradient(to right, #ccc 37%, rgba(125, 195, 125, 0.25) 51%) !important;
}

.medium_util {
    background:rgba(125, 195, 125, 0.5);
}

.medium_utilNA_Absence {
    background: linear-gradient(to right, #ccc 37%, rgba(125, 195, 125, 0.5) 51%);
}

.high_util {
    background: rgba(125, 195, 125, 1);
}

.high_utilNA_Absence {
    background: linear-gradient(to right, #ccc 37%, #5AAC7B 51%);
}

#loadingSFLogo {
    width: 100px;
    display: block;
    margin: 180px auto 20px
}

#FirstTimeLoading {
    background: rgba(255, 255, 255, .9);
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    z-index: 999999999;
    color: #54698D;
    font-size: 20px;
    font-weight: lighter;
    text-align: center;
    position: fixed;
}

.dhx_year_week {
    border-bottom: 1px solid #CECECE;
}

.dhx_cal_data .dhx_year_month {
    background: #D7DFE7;
    color: #16325c;
}

.dhx_scale_bar {
    background: #F7F9FB;
    color: #16325c;
}

.dhx_minical_popup .dhx_scale_bar {
    background: #fff;
}

.dhx_cal_tab,
.dhx_cal_tab_standalone {
    border: 1px solid #d8dde6 !important;
    font-family: 'Salesforce Sans',Arial,sans-serif !important;
    text-overflow: ellipsis !important;
    white-space: nowrap !important;
}

.dhx_cal_tab:hover,
.dhx_cal_tab_standalone:hover {
    background: #f4f6f9 !important;
    text-overflow: ellipsis !important;
    white-space: nowrap !important;
}

.dhx_cal_tab.active {
    background: #D7DFE7 !important;
    text-overflow: ellipsis !important;
    white-space: nowrap !important;
}

#businessHours select {
    color: #000;
    -webkit-appearance: none;
    -moz-appearance: none;
    font-size: 12px;
    background-color: #fff;
    position: relative;
    background-position: bottom 12px right 9px;
    right: -2px;
    top: -10px;
    border-radius: 3px;
    border: 1px solid #d8dde6;
    padding: 8px 6px 7px 7px;
    width: 85px;
    background-image: url(data:image/gif;base64,R0lGODlhCAAFAKIAANvf51VpjVxvkdXa42t9nP///wAAAAAAACwAAAAACAAFAAADEEixTCMsiFHemiU/nDMAXQIAOw==);
    background-repeat: no-repeat;
}

#fromHour {
    border-radius: 3px 0 0 3px !important;
}

#toHour {
    border-radius:0 !important;
    right: 2px !important;
}

.dhx_cal_tab_last {
    border-radius:0 !important;
    text-overflow: ellipsis !important;
    white-space: nowrap !important;
}

.year_tab {
    border-radius: 0 3px 3px 0;
    left: 197px !important;
    text-overflow: ellipsis !important;
    white-space: nowrap !important;
}

.dhx_cal_tab_first,
.dhx_cal_prev_button {
    border-radius: 3px 0 0 3px;
    background-size: 8px 8px;
    text-overflow: ellipsis !important;
    white-space: nowrap !important;
}

.dhx_cal_next_button {
    border-radius: 0 3px 3px 0;
    background-size: 8px 8px;
}

.dhx_cal_today_button {
    border-radius:3px;
    text-overflow: ellipsis !important;
    white-space: nowrap !important;
}

.dhx_cal_navline > div {
    font-family: 'Salesforce Sans',Arial,sans-serif !important;
    font-weight: normal;
    color: #222;
    overflow: hidden;
}

.dhx_cal_tab {
    text-shadow: none !important;
    overflow: hidden;
    /*text-overflow: ellipsis !important;
    white-space: nowrap !important;*/
}


#dhx_minical_icon {
    border-radius: 3px;
    border: 1px solid #D8DDE6;
    padding: 3px 18px 3px 3px;
    background-image: url(data:image/gif;base64,R0lGODlhCAAFAKIAANvf51VpjVxvkdXa42t9nP///wAAAAAAACwAAAAACAAFAAADEEixTCMsiFHemiU/nDMAXQIAOw==);
    background-repeat: no-repeat;
    background-position: top 13px right 6px;
    left: 274px;
}

#dhx_minical_icon:hover {
    background-color: #f4f6f9 !important;
}

#dhx_minical_icon svg {
    width: 24px;
    height: 24px;
    fill: #16325c;
}

.dhx_minical_popup {
    margin-top:3px;
}

.dhx_cal_today_button:hover,
.dhx_cal_prev_button:hover,
.dhx_cal_next_button:hover {
    background-color: #f4f6f9 !important;
    overflow: hidden;
}

.dhx_tooltip_line:nth-child(odd) {
    background: #FFF !important;
}

.dhx_tooltip_line:nth-child(even) {
    background: #ECEEF4 !important;
}

.dhx_tooltip_date {
    background: transparent !important;
}


.dhx_month_head.dhx_year_event {
    background-color: inherit;
}

.dhx_cal_navline .dhx_cal_date {
    font-size: 15px !important;
}