html, body{
    margin:0px;
    padding:0px;
    height:100%;
    overflow:hidden;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    -o-user-select: none;
    user-select: none;
}
.truncate {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.dhx_cal_container, .dhx_cal_navline .dhx_cal_date, .dhx_cal_today_button{
    font-family: 'Salesforce Sans', Arial, sans-serif;
}

.dhx_title {
    font-size: 11px !important;
    padding-top: 5px !important;
}

.dhx_body {
    padding-bottom: 3px !important;
    line-height: 15px !important;
    text-align: center !important;
    font-size: 11px !important;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.dhx_cal_event .dhx_footer {
    background: none !important;
}

.dhx_minical_icon{
    left:auto !important;
    margin-left: 10px;
}

#ganttSettings {
    top: 20px;
}

#defaultCapacity {
    width: 40px;
}

#defCapLabel {
    margin-left: 10px;
    margin-right: 5px;
}

.lightboxLabel {
    color: #16325c;
    font-size: 12px;
    margin-bottom: 3px;
    display: block;
    font-family: 'Salesforce Sans', Arial, sans-serif;
}

.eventContractorCapacity {
    background: rgba(167, 184, 209, 0.73) !important;
    /*background-image: repeating-linear-gradient(-45deg, transparent, transparent 4px, #BFE6D1 5px, #BFE6D1 6px);*/
    border: 1px solid #A7B8D1;
    font-size: 12px;
    color: #16325c;
    z-index: 0;
    border-radius: 3px;
    height: 35px;
    font-family: 'Salesforce Sans', Arial, sans-serif;
}

.eventCapacityDaily {
    background: #A7B8D1 !important;
    /*background-image: repeating-linear-gradient(-45deg, transparent, transparent 4px, #BFE6D1 5px, #BFE6D1 6px) !important;*/
    border: 1px solid #A7B8D1 !important;
}

.eventCapacityWeekly {
    background: #CFD7E6 !important;
    /*background-image: repeating-linear-gradient(-45deg, transparent, transparent 4px, #BFE6D1 5px, #BFE6D1 6px) !important;*/
    border: 1px solid #CFD7E6 !important;
}

.eventCapacityMonthly {
    background: #EEF1F6 !important;
    /*background-image: repeating-linear-gradient(-45deg, transparent, transparent 4px, #E6BFBF 5px, #E6D5BF 6px) !important;*/
    border: 1px solid #EEF1F6 !important;
}

.capacitySelected {
    background: #808080 !important;
    /*background-image: repeating-linear-gradient(-45deg, transparent, transparent 4px, #6E8076 5px, #798A81 6px) !important;*/
    color: #fff !important;
    border: 1px dashed #fff !important;
}

.tooltipLine {
    color: #222;
    margin: 4px 0;
}

.tooltipHR {
    height: 1px;
    width: 100%;
    background: #D5D5D5;
    margin: 12px 0;
}

.tooltipCell {
    display: inline-block;
    width: 105px;
}

.tooltipValue {
    text-transform: capitalize;
    min-width:100px;
}

.tooltipTitle {
}

.expertTooltip {
    border: 1px solid #CECECE;
    box-shadow: 2px 2px 5px #CCC !important;
    border-radius: 3px;
    color: #1c1c1c;
    max-width: 500px;
    padding: 0 !important;

}

.tooltipBody {
    padding: 8px 10px;
    font-family: 'Salesforce Sans', Arial, sans-serif;

}

.capacityLightboxHeader {
    background: #0877bd;
    padding: 8px;
    /*border-radius: 3px 3px 0 0;*/
}

.capacityLightboxName {
    color: #fff;
    font-size: 16px;
}

.capacityLighboxContent {
    padding: 15px;
}


.fieldRow {
    margin-bottom: 10px;
    color: #16325c;
    max-width: 160px;
}

#leftside {
    display: inline-block;
}

.fieldRow input {
    border-radius: 3px;
    border: 1px solid #CCC;
    padding: 5px;
    width: 150px;
}

#rightside {
    display: inline-block;
    width: 162px;
    margin-left: 42px;
    position: relative;
    top: -2px;
}

#rightside input[type="radio"] {
    display:none;
}

#rightside label {
    display: block;
    color: #0877bd;
    background-color: #fff;
    border: 1px solid #0877bd;
    padding: 8px;
    margin-bottom: 20px;
    border-radius: 2px;
    text-align: center;
    cursor: pointer;
}

#rightside input[type="radio"]:checked + label, #rightside input[type="radio"]:active + label:active {
    color: #fff;
    background-color: rgb(0, 57, 107);
    border-color: #085282;
    box-shadow: inset 0 3px 5px rgba(0,0,0,0.125);
}

#rightside label:hover{
    color: #fff;
    background-color: rgb(0, 112, 210);
    border-color: #0070d2;
}

.sub_item_icon,
.sub_item_hk {
    display: none !important;
}

.sub_item_text {
    padding: 0px !important;
    border-top: 0 !important;
    border-bottom: 0 !important;
    cursor: pointer !important;
}

.sub_item_text .sub_item_text {
    padding: 4px 8px !important;
    margin-right: 20px !important;
}

.sub_item_text .fa {
    margin-right: 3px;
}

.sub_item_selected td {
    background: #f1f1f1 !important;
    border-top: 0 !important;
    border-bottom: 0 !important;
    box-shadow: inset 2px 0 0 rgba(8, 119, 189, 1);
}

.dhtmlxMenu_dhx_skyblue_SubLevelArea_Polygon {
    border: 1px solid rgb(207, 215, 219) !important;
    border-top-left-radius: 3px !important;
    border-top-right-radius: 3px !important;
    border-bottom-right-radius: 3px !important;
    border-bottom-left-radius: 3px !important;
    box-shadow: rgba(10, 10, 10, 0.14) !important;
    padding: 0px !important;
    background: rgb(255, 255, 255) !important;
}

.dhtmlxMenu_dhx_skyblue_SubLevelArea_Polygon:nth-child(1),
.dhtmlxMenu_dhx_skyblue_SubLevelArea_Polygon:nth-child(2) {
    margin-left: -15px !important;
}


.LightboxBlackContainer {
    position: fixed;
    position: -ms-page;
    width: 100%;
    height: 100%;
    background: rgba(0,0,0,0.3);
    top: 0;
    left: 0;
    z-index: 1000;
    display:none;
}

#notCapacityBasedLightbox {
    display:none;
}

#capacityLightbox, #multiUpdateLightbox {
    display: none;
}

.multiUpdateLightboxWindow {
    top: 50% !important;
    left: 50% !important;
    transform: translate(-180px, -155px);
}

.durationExplained{
    display:none;
    background-color:rgb(0, 57, 107);
    color:#fff;
    /*border:1px solid #CECECE !important;*/
    -moz-box-shadow:1px 1px 1px #888888 !important;
    -webkit-box-shadow:1px 1px 1px #888888 !important;
    -o-box-shadow:1px 1px 1px #888888 !important;
    box-shadow: 1px 1px 1px #888888 !important;
    border-radius:0 !important;
    width: 175px;
    /*height: 35px;*/
    left: 175px;
    font-size: 12px;
    padding: 7px 2px 16px 10px;
    position: absolute;
    z-index: 11199;
}

/* arrows - :before and :after */
.durationExplained:after, .arrow_box:before {
    right: 100%;
    /*top: 5px;*/
    border: solid transparent;
    content: " ";
    height: 0;
    width: 0;
    position: absolute;
    pointer-events: none;
}

.durationExplained:after {
    border-color: transparent;
    border-right-color: rgb(0, 57, 107);
    border-width: 10px;
    margin-top: -30px;
}
.durationExplained:before {
    border-color: transparent;
    border-right-color: rgb(0, 57, 107);
    border-width: 11px;
    margin-top: -10px;
}

#dailyExplained {
    top: 0px;
}
#weeklyExplained {
    top: 55px;
    width: 205px;
    /*height: 36px;*/
}

#DatesJumpTo {
    color: #747473;
    left: auto;
    right: 220px;
    background: 0 0;
    text-decoration: none;
    width: 35px;
    font-size: 18px;
    font-family: arial;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
    border-radius: 5px;
    height: 30px;
    line-height: 30px;
    border: 1px solid #CECECE;
    cursor: pointer;
}

#DatesJumpTo i {
    margin-top: 6px;
    margin-left: 9px;
    cursor: pointer;
}

.inputError {
    border-color: crimson !important;
}

.eventLabel {
    display: block;
}

.fieldRow label {
    text-transform: capitalize;
    text-overflow: ellipsis;
    white-space: nowrap;
}
/*-----------------------------------modals-----------------------------*/

.LightboxContainer {

    width: 980px;
    height: calc(100% - 320px);
    min-height: 580px;
    max-height: 800px;
    background: #fff;
    margin: 55px auto 0;
    padding: 0;
    position: relative;
    border-radius: 8px;
    color: #16325c;
    font-family: 'Salesforce Sans', Arial, sans-serif;
}

.capacityLightboxPopUp {
    padding: 0;
    position: absolute;
    top: 100px;
    left: 200px;
    z-index: 10001;
    background-color: white;
    border-radius: 2px;
    width: 400px;
    height: 335px;
    font-family: 'Salesforce Sans', Arial, sans-serif;
}

.notCapacityBasedLightboxWindow {
    height: 180px;
    top:50%;
    left:50%;
    transform: translate(-50%, -50%);
}

.capacityLightboxPopUp h1 {
    font-size: 16px;
    margin-right: 10px;
    float: left;
    margin: 4px 10px 0 0;
    font-family: 'Salesforce Sans', Arial, sans-serif !important;
    font-weight: 200;
}


.lightboxControllers {
    position: absolute;
    bottom: 0;
    padding: 10px 15px;
    background: #F4F6F9;
    width: calc(100% - 30px);
    border-bottom-left-radius: 8px;
    border-bottom-right-radius: 8px;
    border-top: 2px solid #D8DDE6;
}

.lightboxControllers .lightboxSaveButton {
    float: right;
}

.lightboxSaveButton {
    border: #0070d2;
    background: rgb(0, 112, 210);
    color: #FFFFFF;
    border-radius: 2px;
    cursor: pointer;
    display: inline-block;
    padding: 10px 12px;
    font-size: 14px;
}

.lightboxSaveButton:hover {
     background: rgb(0, 95, 178);
 }

.lightboxSaveButton:active {
     background:rgb(0, 57, 107);
 }

.lightboxHeaderContainer {

    padding: 20px 15px 0 15px;
    color: #16325c;
    margin-bottom: 15px;
    box-shadow: inset 0 -2px 0 rgb(216, 221, 230);
    overflow: hidden;
}

/*.lightboxHeaderContainer span {
    margin: 0 7px;
    font-size: 13px;
    display: inline-block;
    padding: 6px 15px 21px 15px;
    background: #FFF;
    border-bottom: 2px solid #D8DDE6;
    text-align: center;
    margin-right: 0;
    cursor: pointer;
    color: #16325c;
    float: left;
    text-transform: uppercase;

}*/

.CloseLightbox {
    top: -39px;
    cursor: pointer;
    fill: #FFF !important;
    float: right;
    position: absolute;
    right: 0;
    width: 30px !important;
    height: 30px !important;
}
.ExtendedForm {
    float: right;
    font-size: 18px;
    margin-top: 5px;
}

.ExtendedForm a,
.ExtendedForm a:visited
.ExtendedForm a:active {
      color: #0070D2;
      text-decoration: none;
}


.ExtendedForm .slds-icon {
    width: 20px;
    height:20px;
    fill:#0070d2;
}

.light-box-header {
    margin-bottom: 22px !important;
}

.slds-theme--alert-texture {
    background-image: linear-gradient(45deg,rgba(0,0,0,.025) 25%,transparent 25%,transparent 50%,rgba(0,0,0,.025) 50%,rgba(0,0,0,.025) 75%,transparent 75%,transparent);
    background-size: 64px 64px;
}

.slds-theme--error {
    color: #fff;
    background-color: #c23934 !important;
    font-family: 'Salesforce Sans', Arial, sans-serif !important;
    font-weight: 200;
    text-align: center;
    padding: 20px;
    font-size: 16px;
    border-top-right-radius: 2px;
    border-top-left-radius: 2px;
}

.notCapacityBasedContent {
    padding: 15px;
    text-align: center;
}

/*

.ExtendedForm {
    right: 20px;
    position: absolute;
    top: -4px;
    margin: 15px 16px 0 0 !important;
    color: #fff !important;
    cursor: pointer;
}

.ExtendedForm a,
.ExtendedForm a:visited
.ExtendedForm a:active {
    color: #fff !important;
    text-decoration: none !important;
}

.ExtendedForm a:hover {
    text-decoration: underline !important;
    color: #fff !important;
}*/
