body {
	padding: 0;
	margin: 0;
	height: 100%;
	width: 100%;
	position: absolute;
}

#FSLTextLogo {
    position: relative;
    font-size: 16px;
    top: -8px;
    margin: 0 6px 0 4px;
}

#ServiceExpertHeader {
	background: #FFFFFF;
    padding: 5px 10px;
    height: 34px;
    box-shadow: inset 0 -1px 0 rgb(215, 223, 231), 0 2px 6px rgba(84, 105, 141, 0.13);
    z-index: 10;
    position: relative;
}

#ServiceExpertHeader a {
	color: #54698D !important;
    font-size: 14px;
    padding: 5px 17px 5px 15px;
    text-decoration: none;
    position: relative;
}

#ServiceExpertHeader a:hover {
	border-decoration: underline;
}

#ServiceExpertHeader a:first-child {
	margin-left: 10px;
}

#HeaderLinksContainer {
	display: inline-block;
	position: relative;
	top: -7px;
}

#serviceExpertApp {
	height: calc(100% - 44px);
}

#SmartPanelContainer {
	height: calc(100% - 102px);
	margin-bottom: 0px;
}

#SearchEmployeesOnGanttContainer {
	top: 14px !important;
}

#LockGanttContainer {
    top: 69px !important;
}

#breakCreator {
	top: 69px !important;
}

#WhiteLogo {
	height: 25px;
	margin-top: 5px;
	margin-right: 5px;

}
#userDetails {
	position: absolute;
    right: 10px;
    top: 15px;
    color: #54698D;
    font-size: 13px;
}