body, h1, button {
    font-family: 'Salesforce Sans',Arial,sans-serif !important;
}

h1 {
    display: block;
    font-size: 16px;
    font-weight: normal;
    padding: 10px 2px;
}

#List {
    width: 360px;
    border-right: 1px solid #E0E5EE;
    height: 100%;
    position: absolute;
    overflow-y: auto;
}

#GraphContainer {
    width: calc(100% - 361px);
    height: 100%;
    position: absolute;
    right: 0;
    text-align: center;
}

.service-parent {
    padding: 10px;
    background: #f7f9fb;
    border-bottom: 1px solid #e0e5ee;
    font-size: 13px;
    color: #16325c;
    cursor: pointer;
}

.service-related {
    padding: 10px;
    font-size: 13px;
    position: relative;
}


.service-related:last-child {
    border-bottom: 1px solid #e0e5ee;
}

.relations-collapse {
    background: #fff;
    display: inline-block;
    width: 13px;
    height: 13px;
    text-align: center;
    border: 1px solid #e0e5ee;
    font-size: 12px;
    margin-right: 5px;
}

.relation-delete {
    border: 1px solid #ec4f4f;
    font-size: 14px;
    padding: 1px 6px 2px 6px;
    border-radius: 3px;
    background: #ffffff;
    color: #ec4f4f;
    float: right;
    cursor: pointer;
    display: none;
    position: absolute;
    right: 5px;
    top: 7px;
}

.service-related:hover {
    background: #e0e5ee;
}

.service-related:hover .relation-delete {
    display: block;
}

.input-sa {
    font-size: 13px;
    border-radius: 3px;
    border: 1px solid #d8dde6;
    padding: 4px 8px;
    width: 72px;
    margin: 5px 3px;
}

.select-sa {
    appearance: none;
    -webkit-appearance: none;
    -moz-appearance: none;
    font-size: 13px;
    border-radius: 3px;
    border: 1px solid #d8dde6;
    padding: 4px 8px;
    margin: 5px 0;
    z-index: 20;
    position: relative;
    background: none;
    padding-right: 20px;
    width: 151px;
}

#AddNew {
    padding: 5px;
    border-bottom: 1px solid #e0e5ee;
}

#AddNew button {
    border: 1px solid #0070d2;
    background: #0070d2;
    color: #FFF;
    border-radius: 3px;
    cursor: pointer;
    width: 100%;
    padding: 10px;
    font-size: 14px;
    font-weight: normal;
    margin: 10px 0 6px 0;
}

#AddNew button:hover {
    background: #0066bf;
    border: 1px solid #0066bf;
}

#SameResourceContainer {
    margin: 4px 0 1px 0;
}

.select-arrow {
    position: absolute;
    margin: 12px 0 0 -17px;
    color: #b3b8c1;
    transform: scaleX(1.7) rotate(180deg);
    font-size: 9px;
    z-index: 10;
}

.lightbox-container {
    position: fixed;
    width: 100%;
    height: 100%;
    background: rgba(126,140,153,.8);
    top: 0;
    left: 0;
    z-index: 1000;
}

#add-current {
    float: right;
    border: 1px solid #d8dde6;
    padding: 5px 12px 5px 12px;
    border-radius: 3px;
    margin-top: 4px;
    cursor: pointer;
    color: #0070d2;
}

.lightbox {
    max-width: 800px;
    height: calc(100% - 320px);
    max-height: 550px;
    background: #fff;
    margin: 50px auto;
    padding: 15px;
    position: relative;
    border-radius: 8px;
    color: #16325c;
}

#ServiceListContainer {
    height: calc(100% - 100px);
    position: relative;
    overflow-y: auto;
    padding-top: 5px;
    border-top: 1px solid #e0e8ef;
    margin-top: 10px;
}

.service-row {
    padding: 5px;
    cursor: pointer;
    white-space: nowrap;
}

.service-row:hover {
    background: #e0e5ee;
}

.service-cell {
    font-size: 13px;
    padding: 6px;
}

.close-button {
    display: inline-block;
    color: #fff;
    position: relative;
    left: calc(50% + 400px);
    top: 40px;
    font-size: 24px;
    transform: scaleY(0.8);
    cursor: pointer;
}

table tr:first-child td {
    padding: 10px 6px;
    font-size: 12px;
    line-height: 1.25;
    color: #54698d;
    text-transform: uppercase;
    letter-spacing: .0625rem;
}

iframe {
    width: 100%;
    height: calc(100% - 23px);
    border: 0;
}

table {
    border-spacing: 0px;
}



#DagrananaBatman {
    height: calc(100% - 65px);
    width: 100%;
    overflow: hidden;
}

.node {
    white-space: nowrap;
}

.node rect,
.node circle,
.node ellipse {
    /*stroke: #000;*/
    fill: #fff;
    stroke-width: 1.5px;
}

.cluster rect {
    fill: #d9fbff;
    stroke-width: 1.5px;
}

.edgePath path.path {
    stroke: #333;
    stroke-width: 1.5px;
    fill: none;
}

.relation-name {
    color:#0070d2;
    cursor: pointer;
}

#NoChainFound {
    width: 60%;
    margin: 50px auto;
    font-size: 24px;
    color: #949eaf;
    line-height: 36px;
    position: absolute;
    top: 0;
    padding: 50px 20%;
    text-align: center;
    z-index: 2;
}


.node b {
    width: 100%;
    display: inline-block;
    padding: 0 0 5px 0;
    margin-bottom: 5px;
    border-bottom: 1px solid #000;
}

#ScheduleButton {
    background: #0070d2;
    color: #FFF;
    border-radius: 3px;
    cursor: pointer;
    padding: 12px;
    font-size: 18px;
    font-weight: normal;
    margin: 0 20px;
}

#ScheduleButton:hover {
    background: #0066bf;
}


.view-in-gantt {
    width: 100% !important;
    height: 100% !important;
}

.view-in-gantt #DagrananaBatman {
    height: 100% !important;
}


#DagrananaBatman {
    cursor: move;
}


#recenter-graph {
    background: #fff;
    border-radius: 2px;
    cursor: pointer;
    border: 1px solid #d8dde6;
    padding: 7px 13px;
    position: absolute;
    right: 12px;
    top: 11px;
    color: #0070d2;
    width: 78px;
}

#filter-text {
    font-size: 13px;
    border-radius: 3px;
    border: 1px solid #d8dde6;
    padding: 4px 8px;
    margin: 5px 0;
    z-index: 20;
    position: relative;
    background: none;
    padding-right: 20px;
    width: 110px;
    margin-left: 4px;
}




#SchedulingInProgress {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: calc(9000 + 2);
    background-color: rgba(126,140,153,.8);
    visibility: visible;
    opacity: 1;
    transition: opacity .2s ease,visibility 0s;
    transition-delay: 0s,.3s;
    text-align: center;
    font-size: 20px;
}

#SchedulingResultTable {
    width: 70%;
    max-height: 75%;
    background: #fff;
    margin: 50px auto;
    padding: 15px;
    position: relative;
    border-radius: 8px;
    color: #16325c;
    text-align: left;
    overflow-y: auto;
}

#SchedulingResultTable table {
    font-size: 13px;
    width: 100%;
}

#SchedulingResultTable table td {
    padding: 9px 6px;
}

.schedule-error {
    background: #ffe0e0;
}

.scheduling {
    background: #ecf1f3;
    font-weight: bold;
}

#SchedulingInProgress .close-button {
    left: 35% !important;
}