
        .dhx_title {
            font-size: 11px !important;
            padding-top: 5px !important;
        }
        
        
        .dhx_cal_event .dhx_footer { 
            background: none !important;
        }

        .eventStatusNew .dhx_title,
        .eventStatusNew .dhx_body {
            background: #A7E2D6;
            color: #1B615E;
        }
        
        .eventStatusAssigned .dhx_title,
        .eventStatusAssigned .dhx_body {
            background: #FFCE36;
            color: #644D06;
            text-overflow: ellipsis !important;
            white-space: nowrap !important;
            font-size:xx-small !important;
        }
        
        .eventStatusDispatched .dhx_body,
        .eventStatusDispatched .dhx_title {
            background: #92D9F7;
            color: #125977;
            text-overflow: ellipsis !important;
            white-space: nowrap !important;
            font-size:xx-small !important;
        }
        
        .eventStatusTravel .dhx_body,
        .eventStatusTravel .dhx_title {
            background: #D495F4;
            color: #60206C;
            text-overflow: ellipsis !important;
            white-space: nowrap !important;
        }
        
        .eventStatusOnSite .dhx_body,
        .eventStatusOnSite .dhx_title {
            background: #D8C68B;
            color: #352404;
            text-overflow: ellipsis !important;
            white-space: nowrap !important;
        }
        
        .eventStatusCompleted .dhx_body,
        .eventStatusCompleted .dhx_title {
            background: #A3DF6D;
            color: #1C6708;
            text-overflow: ellipsis !important;
            white-space: nowrap !important;
        }
        
        .eventStatusIncomplete .dhx_body,
        .eventStatusIncomplete .dhx_title {
            background: #F27D7D;
            color: #3A0707;
            text-overflow: ellipsis !important;
            white-space: nowrap !important;
        }
        
        .eventCustomStatus .dhx_body,
        .eventCustomStatus .dhx_title {
            background: #B7C9EA;
            color: #2D3542;
            text-overflow: ellipsis !important;
            white-space: nowrap !important;
        }
        .NA_Break .dhx_body,
        .NA_Break .dhx_title{
           background-color: #5e698f;
          /*  background-color: transparent;*/
          /*  background:repeating-linear-gradient(45deg,#5e698f,#5e698f 12.5px,#535C7D 12.5px,#535C7D 25px)!important;*/
           /* color: repeating-linear-gradient(45deg,rgba(94, 105, 143, 1),rgba(94, 105, 143, 1) 12.5px,rgba(83, 92, 125, 1) 12.5px,#rgba(83, 92, 125, 1) 25px)!important;*/
            background: repeating-linear-gradient(45deg,rgb(94,105,143),rgb(94,105,143) 12.5px,rgb(83,92,125) 12.5px,rgb(83,92,125) 25px) !important;
             text-overflow: ellipsis !important;
            white-space: nowrap !important;
        }
        .dhx_cal_event.NA_Break {
            background:-webkit-repeating-linear-gradient(45deg,#5e698f,#5e698f 12.5px,#535C7D 12.5px,#535C7D 25px)!important;
            background: repeating-linear-gradient(45deg,rgb(94,105,143),rgb(94,105,143) 12.5px,rgb(83,92,125) 12.5px,rgb(83,92,125) 25px) !important;

        }


        .imgStyle{
        /*width: 14px;
        height: 14px;
        position: absolute;
        left: 1%;
        top:20%;*/
        display:none;
       /*transform: translateX(70px) translateY(3px);*/
      }
      #imgStyleForMonth{
         width: 14px;
        height: 14px;
        position: absolute;
       /* position:static;*/
        left: 75%;
        transform: translateX(31px) translateY(3px);
        background-color:#5e698f;
      }
       #imgNaStyleForMonth{
         width: 14px;
        height: 14px;
        position: absolute;
       /* position:static;*/
        left: 50%;
        transform: translateX(31px) translateY(-1px);
      }

        .NA_Absence_NoTravel .dhx_body,
        .NA_Absence_NoTravel .dhx_title{
            color: #3A0707;
            background-color: transparent;
             text-overflow: ellipsis !important;
            white-space: nowrap !important;
            /*background:-webkit-repeating-linear-gradient(45deg,rgba(215,223,231,1),rgba(215,223,231,1) 12.5px,rgba(206, 214, 221,1) 12.5px,rgba(206, 214, 221,1) 25px)!important;
           background: repeating-linear-gradient(45deg,rgba(215,223,231,1),rgba(215,223,231,1) 12.5px,rgba(206, 214, 221,1) 12.5px,rgba(206, 214, 221,1) 25px)!important;*/
        }

         .dhx_cal_event.NA_Absence_NoTravel {
            background:-webkit-repeating-linear-gradient(45deg,rgba(215,223,231,1),rgba(215,223,231,1) 12.5px,rgba(206, 214, 221,1) 12.5px,rgba(206, 214, 221,1) 25px)!important;;
            background: repeating-linear-gradient(45deg,rgba(215,223,231,1),rgba(215,223,231,1) 12.5px,rgba(206, 214, 221,1) 12.5px,rgba(206, 214, 221,1) 25px)!important;;
        }
        
        #businessHours {
            position: fixed;
            top: 19px;
            right: 150px;
            z-index: 10;
        }
        
        #Apply {
            display: inline-block;
            padding: 3px 8px;
            background: #0877bd;
            border-radius: 3px;
            color: #fff;
            font-size: 11px;
            position: relative;
            top: -1px;
            cursor: pointer;
        }
        
        #Apply:hover {
            background: #0A6EAD;
        }
        
        #Apply:active {
            top: 0px;
        }
        
        .dhx_cal_today_button {
            width: 52px !important;
            right: 90px !important;
        }
        
        .dhx_cal_prev_button,
        .dhx_cal_next_button {
            width: 34px !important;
        }
        
        .dhx_cal_prev_button {
            right: 49px !important;
        }

        .lightboxLabel {
            color: #676767;
            font-size: 12px;
            margin-bottom: 3px;
            display: block;
        }

        .LightboxPopUp {
            position: absolute;
            top:51px;
            left:239px;
            z-index: 10001;
            background-color: white;    
            width: 300px;
            box-shadow: 10px 10px 5px -8px rgba(0,0,0,0.75);
            border-radius: 10px;
            border: 1px solid #CCC;

        }

        .LightboxHeader {
            background: #fff;
            /*border-radius: 10px;*/
            padding: 8px;
            border-bottom: 2px solid #D8DDE6;
        }
        .LightboxName {
            color: #55698D;
            font-size: 19px;
        }

        .LightboxClose {
            right: 9px;
            position: absolute;
            top: 8px;
            color: #55698D;
            /* border: 1px solid #fff; */
            border-radius: 50%;
            padding: 3px 5px;
            background: #fff;
            cursor: pointer;
        }
        .LighboxContent {
            padding: 15px;
        }

        .fieldRow {
            margin-bottom: 10px;
        }

        #leftside {
            display: inline-block;
        }

        #leftside .fieldRow input {
            border-radius: 3px;
            border: 1px solid #CCC;
            padding: 5px;
            width: 66px;
        }

        input[type='radio'] {
            margin-right: -14px;
        }
         #leftside .fieldRow select {
            border-radius: 3px;
            border: 1px solid #CCC;
            padding: 5px;
            width: 70px;
        }

        .LightboxButtons {
            border-radius: 0 0 3px 3px;
            padding: 0 10px 10px 10px;
        }

        .Btn {
            background: #0877bd;
            padding: 8px;
            width: 100px;
            font-size: 14px;
            color: #fff;
            text-align: center;
            margin: 0 auto;
            border-radius: 3px;
            cursor: pointer;
           /* margin-bottom: 10px;*/
            margin-top: 13px;  /**/
        };

        .printIcon {
            position: absolute;
            color: #B4AEAC !important;
            background: #fff;
            cursor: pointer !important;
            top: 10px;
           margin-left: 254px !important;
           margin-top: 5px !important;           
        }

        #rightside {
            display: inline-block;
            width: 162px;
            margin-left: 42px;
            position: relative;
            top: -2px;
        }
         .dhx_cal_event_clear.dhx_cal_event_line_start.dhx_cal_event_line_end{
             text-overflow: ellipsis !important;
            white-space: nowrap !important;
        }

     