body {
    height: 100%;
    width: 100%;
    position: absolute;
    font-family: 'Salesforce Sans',Arial,sans-serif;
}

iframe {
    width: 100%;
    height: calc(100% - 57px);
    border: 0;
}

#ResourcePagesTabs {
    padding: 10px;
}


.resource-tab {
    padding: 10px 3px;
    min-width: 94px;
    text-align: center;
    cursor: pointer;
    text-transform: uppercase;
    letter-spacing: .88px;
    font-size: 13px;
    display: inline-block;
}

.resource-tab:hover,
.selected-tab {
    box-shadow: inset 0 -2px 0 0 #0070d2;
    color: #16325c;
}