body,html{
	background-color: #fff;
  }
.bs{
	background-color: #fff;
	}

.status-button {
	padding: 15px;
	width: 100%;
	font-weight: normal;
	font-size: 16px;
}

#UpdatedStatusSeccessfully {
	padding: 50px 10px 20px 10px;
	text-align: center;
	font-size: 18px;
}

#BackToTheFirstPage {
    position: absolute;
    top: 15px;
    left: 5px;
    padding: 8px;
    color: #55698D;
    cursor: pointer;
    font-size: 18px;
    display: none;
    font-size: 14px;
}

.comment-container,
.statuses-container {
    padding: 20px 15px;
    background-color: #fff;
    overflow-y: auto;
    height: calc(100vh - 77px);
}

.save-incomp-btn {
	text-align: center;
    padding: 15px;
    margin-top: 20px
}

select {
    color: #54698d;
    border: 1px solid #D8DDE6;
    border-radius: 3px;
    padding: 10px;
    background-color: #FFFFFF;
    font-size: 14px;
    -webkit-appearance: none;
    background-image: url(data:image/gif;base64,R0lGODlhCAAFAKIAANvf51VpjVxvkdXa42t9nP///wAAAAAAACwAAAAACAAFAAADEEixTCMsiFHemiU/nDMAXQIAOw==);
    background-repeat: no-repeat;
    background-position: right 14px top 16px;
    width: 100%;
}

.inputLabel {
	margin: 15px 0 10px 0;
	text-align: center;
}

.sig-page-button {
    padding: 15px;
    width: calc(50% - 46px);
    display: inline-block;
    margin: 10px 5px;
    font-size: 16px;
}

#noStatusTransition {
	display: none;
    text-align: center;
    padding: 40px 10px;
    font-size: 18px;
}





.BackButton {
	color: #168dda !important;
	background: #fff !important;
	font-size: 18px !important;
	border-radius: 3px !important;
	padding: 11px 8px;
	border: 1px solid #168dda !important;
	text-align: center !important;
	cursor: pointer !important;
	width: 97% !important;
	display: inline;
	bottom: 10px;
	margin-top: 50px !important;
}

.dn {
	display: none !important;
}

.has-error .validatedInput {
	border-color: #a94442;
	-webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
	box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
}

.btn-group-padding {
	padding: 3px;			
	text-align: center !important;
}

#incompleteBtn {
	text-align: center !important;
	float: right;
	margin-right: 20px;
	margin-top: 5px;
}

div.other-reason-container {
	padding-bottom: 10px;
}

.SaveClearbtn {
	color: #168dda !important;
	background: #fff !important;
	font-size: 18px !important;
	border-radius: 3px !important;
	padding: 11px 8px !important;
	border: 1px solid #168dda !important;
	margin: 15px 20px 10px 12px !important;
	font-family: 'Varela Round', sans-serif !important;
	text-align: center !important;
	cursor: pointer !important;
	outline: none !important;
}

.button-status-expert {
	background: #fff !important;
	color: #575757 !important;
	border: 1px solid #E0DBDB !important;
	border-radius: 4px !important;
	width: 98% !important;
	display: block !important;				/*margin: 0 1% !important;*/
	padding: 14px 0 !important;
	outline: none !important;
}

.button-status-expert:hover {
	box-shadow: 0 2px 6px rgba(0, 0, 0, 0.10);
	border-color: #C7C7C7 !important;
	color: #168DDA !important;
}

.button-status-expert:active {
	box-shadow: 0 2px 6px rgba(0, 0, 0, 0.10);
	border-color: #168DDA !important;
	background-color: #168DDA !important;
	color: #fff !important;
	position: relative;
	top: 1px;
}



#signature canvas {
	width: 100% !important;
}

#PinnedService {
	text-align: center;
	margin-top: 50px;
	font-size: 20px;
}

.fa-thumb-tack {
	font-size: 50px !important;
	color: #8C8C8C;
}

#PinnedText {
	margin-top: 20px;
	color: #8C8C8C;
}